global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: "kaslite-morphogenetic-engine"
    static_configs:
      - targets: ["kaslite-app:8000"]
    scrape_interval: 10s
    metrics_path: "/metrics"

  - job_name: "inference-server"
    static_configs:
      - targets: ["inference:8080"]
    scrape_interval: 5s # More frequent for inference monitoring
    metrics_path: "/metrics"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
