# Architecture Search Configuration
# Focused on finding optimal network architectures

# Core architecture parameters
num_layers: [2, 4, 6, 8, 12, 16, 20]
seeds_per_layer: [1, 2, 3, 4, 5]
hidden_dim: 32,64,128,256,512 # Comma-separated

# Morphogenetic parameters
blend_steps: [10, 20, 30, 50, 100]
progress_thresh: [0.5, 0.6, 0.7, 0.8]
drift_warn: [0.05, 0.1, 0.15, 0.2]

# Keep dataset and training simple
problem_type: moons
lr: 0.001
n_samples: 1000
adaptation_epochs: 100
