# Dataset Comparison Configuration
# Compare performance across different datasets and dimensions

# Dataset variations
problem_type: ["spirals", "moons", "clusters", "spheres", "complex_moons"]
input_dim: [2, 3, 4, 5, 6]
n_samples: [500, 1000, 2000, 4000]

# Dataset-specific parameters that apply when relevant
noise: [0.1, 0.2, 0.3] # For spirals and spheres
moon_noise: [0.05, 0.1, 0.15] # For moons datasets
cluster_count: [2, 3, 4, 5] # For clusters
sphere_count: [2, 3, 4] # For spheres

# Keep model architecture fixed
num_layers: 8
seeds_per_layer: 1
hidden_dim: 128
lr: 0.001

# Training consistency
batch_size: 64
train_frac: 0.8
