# Quick Test Sweep
# Minimal configuration for fast testing

num_layers: [4, 8]
seeds_per_layer: 1,2
lr: [0.001, 0.003]

# Fast execution settings
problem_type: spirals
n_samples: 500
warm_up_epochs: 10
adaptation_epochs: 20
batch_size: 32
